name: "\U0001F40A Terrarium Check"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
  cancel-in-progress: true
'on':
  pull_request: null
  workflow_dispatch: null
jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/docker-mirror/python:3.11.0
    strategy:
      fail-fast: false
      matrix:
        value:
        - bi_ci
        - dl_gitmanager
        - dl_repmanager
    name: "\U0001F40A[pytest] ${{ matrix.value }}"
    steps:
    - uses: datalens-tech/cleanup-folder-action@v1
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup common tools
      run: pip install --no-input poetry
    - name: Install dependencies
      run: 'cd "terrarium/${{ matrix.value }}"

        poetry -v install --with tests --without mypy

        '
    - name: Pytest
      run: 'cd "terrarium/${{ matrix.value }}"

        poetry run pytest .

        '
  mypy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/docker-mirror/python:3.11.0
    strategy:
      fail-fast: false
      matrix:
        value:
        - bi_ci
        - dl_cli_tools
        - dl_gitmanager
        - dl_repmanager
    name: "\U0001F40A[mypy] ${{ matrix.value }}"
    steps:
    - uses: datalens-tech/cleanup-folder-action@v1
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup common tools
      run: pip install --no-input poetry
    - name: Install dependencies
      run: 'cd "terrarium/${{ matrix.value }}"

        poetry -v install --with mypy --without tests

        '
    - name: Mypy
      run: 'cd "terrarium/${{ matrix.value }}"

        poetry run mypy .

        '
